### GET request to example server
GET http://localhost:8080/api/runs

###


PUT http://localhost:8080/api/runs/5

## Create a new run
###
POST http://localhost:8080/api/runs
content-Type: application/json

{
  "id": 8,
  "title": "Dovah's run",
  "startedOn": "2026-02-07T10:47:10.770936704",
  "completedOn": "2026-02-07T12:47:10.77094752"
}

###
DELETE http://localhost:8080/api/runs/8
